services:
  postgres:
    image: postgres:15.3-alpine
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bitly
    ports:
      - "5433:5432"
    volumes:
    - postgres_data:/var/lib/postgresql/data

  localstack:
    image: localstack/localstack:latest
    container_name: localstack_container
    environment:
    - SERVICES=s3,sqs
    - DEFAULT_REGION=us-east-1
    - AWS_ACCESS_KEY_ID=test
    - AWS_SECRET_ACCESS_KEY=test
    - DATA_DIR=/tmp/localstack/data
    ports:
    - "4566:4566"
    volumes:
    - localstack_data:/var/lib/localstack

volumes:
    postgres_data:
    localstack_data:
